apiVersion: v1
kind: Service
metadata:
  name: v2rayn
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "v2rayn"
    port: 8080
  selector:
    app: v2rayn
